// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TreineMais.Infrastructure.Context;

#nullable disable

namespace TreineMais.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251208221031_UpdateDate")]
    partial class UpdateDate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TreineMais.Domain.Entity.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Exercises", (string)null);
                });

            modelBuilder.Entity("TreineMais.Domain.Entity.Profile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("Date");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Goals")
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ComplexProperty<Dictionary<string, object>>("Height", "TreineMais.Domain.Entity.Profile.Height#Height", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<float>("Value")
                                .HasColumnType("decimal(3,2)");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Weight", "TreineMais.Domain.Entity.Profile.Weight#Weight", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<float>("Value")
                                .HasColumnType("decimal(3,2)");
                        });

                    b.HasKey("UserId");

                    b.ToTable("Profiles", (string)null);
                });

            modelBuilder.Entity("TreineMais.Domain.Entity.Routine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("UserId");

                    b.ToTable("Routines", (string)null);
                });

            modelBuilder.Entity("TreineMais.Domain.Entity.Training", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("RoutineId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("RoutineId");

                    b.HasIndex("UserId");

                    b.ToTable("Trainings", (string)null);
                });

            modelBuilder.Entity("TreineMais.Domain.Entity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.ComplexProperty<Dictionary<string, object>>("Login", "TreineMais.Domain.Entity.User.Login#Login", b1 =>
                        {
                            b1.IsRequired();

                            b1.ComplexProperty<Dictionary<string, object>>("Email", "TreineMais.Domain.Entity.User.Login#Login.Email#Email", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(300)
                                        .HasColumnType("character varying(300)");
                                });

                            b1.ComplexProperty<Dictionary<string, object>>("Password", "TreineMais.Domain.Entity.User.Login#Login.Password#Password", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasColumnType("text");
                                });
                        });

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("TreineMais.Domain.Entity.Exercise", b =>
                {
                    b.HasOne("TreineMais.Domain.Entity.User", null)
                        .WithMany("Exercises")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TreineMais.Domain.Entity.Profile", b =>
                {
                    b.HasOne("TreineMais.Domain.Entity.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("TreineMais.Domain.Entity.Profile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TreineMais.Domain.Entity.Routine", b =>
                {
                    b.HasOne("TreineMais.Domain.Entity.User", null)
                        .WithMany("Routines")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TreineMais.Domain.Entity.Training", b =>
                {
                    b.HasOne("TreineMais.Domain.Entity.Routine", null)
                        .WithMany("Trainings")
                        .HasForeignKey("RoutineId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TreineMais.Domain.Entity.User", null)
                        .WithMany("Trainings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("TreineMais.Domain.Entity.TrainingExercise", "Exercises", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<int>("TrainingId")
                                .HasColumnType("integer");

                            b1.Property<int>("ExerciseId")
                                .HasColumnType("integer");

                            b1.Property<int>("Reps")
                                .HasColumnType("integer");

                            b1.Property<int>("Sets")
                                .HasColumnType("integer");

                            b1.HasKey("Id", "TrainingId");

                            b1.HasIndex("ExerciseId");

                            b1.HasIndex("TrainingId");

                            b1.ToTable("TrainingExercises", (string)null);

                            b1.HasOne("TreineMais.Domain.Entity.Exercise", null)
                                .WithMany()
                                .HasForeignKey("ExerciseId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("TrainingId");

                            b1.OwnsOne("TreineMais.Domain.ValueObject.Weight", "Weight", b2 =>
                                {
                                    b2.Property<int>("TrainingExerciseId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("TrainingExerciseTrainingId")
                                        .HasColumnType("integer");

                                    b2.Property<float>("Value")
                                        .HasColumnType("real")
                                        .HasColumnName("WeightValue");

                                    b2.HasKey("TrainingExerciseId", "TrainingExerciseTrainingId");

                                    b2.ToTable("TrainingExercises");

                                    b2.WithOwner()
                                        .HasForeignKey("TrainingExerciseId", "TrainingExerciseTrainingId");
                                });

                            b1.Navigation("Weight")
                                .IsRequired();
                        });

                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("TreineMais.Domain.Entity.Routine", b =>
                {
                    b.Navigation("Trainings");
                });

            modelBuilder.Entity("TreineMais.Domain.Entity.User", b =>
                {
                    b.Navigation("Exercises");

                    b.Navigation("Profile")
                        .IsRequired();

                    b.Navigation("Routines");

                    b.Navigation("Trainings");
                });
#pragma warning restore 612, 618
        }
    }
}
